# Table of Contents
 <p>

In [4]:
import numpy as np

In [9]:
from itertools import combinations

In [5]:
t_a = np.array([['a','m','1'],['a','m','2'],['b','n','1'],['b','n','1'],['b','n','1'],['b','n','2'],['a1','o','1']])

In [6]:
t_a

array([['a', 'm', '1'],
       ['a', 'm', '2'],
       ['b', 'n', '1'],
       ['b', 'n', '1'],
       ['b', 'n', '1'],
       ['b', 'n', '2'],
       ['a1', 'o', '1']], 
      dtype='<U2')

In [153]:
np.count_nonzerocols[np.where(cluster=='1')]

array(['a', 'b', 'b', 'b', 'a1'], 
      dtype='<U2')

In [35]:
def vdm(cols,clu):
    m_u = np.unique(cols,return_counts=True)
    vdm_value = np.zeros(len(list(combinations(m_u[0],2))))
    for k in np.unique(clu):
        m_ui = np.unique(cols[np.where(clu == k)],return_counts=True)
        m_ui0,m_ui1 = m_ui
        array_diff = np.setdiff1d(m_u[0],m_ui[0])
        print(array_diff)
        m_ui1 = np.append(m_ui1,[0]*len(array_diff))
        m_ui0 =  np.append(m_ui0,array_diff)
        print(m_ui0,m_ui1,)
        s_mui = sorted(zip(m_ui0,m_ui1),key=lambda x:x[0])
        s_mui1 = np.array([y for x,y in s_mui])
        clu_rate = zip(m_u[0],s_mui1/m_u[1])    
        clu_sq = [np.square(c[0][1]-c[1][1]) for c in combinations(clu_rate,2)]
        print(clu_sq)
        vdm_value += np.array(clu_sq)
        print(vdm_value)
    ret = dict(zip(combinations(m_u[0],2),vdm_value))
    return ret


In [42]:
vdm(t_a[:,1],t_a[2])

['m' 'o']
['n' 'm' 'o'] [1 0 0]
[0.0625, 0.0, 0.0625]
[ 0.0625  0.      0.0625]
['n' 'o']
['m' 'n' 'o'] [1 0 0]
[0.25, 0.25, 0.0]
[ 0.3125  0.25    0.0625]
['n' 'o']
['m' 'n' 'o'] [1 0 0]
[0.25, 0.25, 0.0]
[ 0.5625  0.5     0.0625]


{('m', 'n'): 0.5625, ('m', 'o'): 0.5, ('n', 'o'): 0.0625}

In [ ]:
class 